list = []

list.append(-113)
print(f"slot 0 has a {list[0]}")
list.append(-113)
print(f"slot 1 has a {list[1]}")
list.append(-113)
print(f"slot 2 has a {list[2]}")
list.append(-113)
print(f"slot 3 has a {list[3]}")
list.append(-113)
print(f"slot 4 has a {list[4]}")
list.append(-113)
print(f"slot 5 has a {list[5]}")
list.append(-113)
print(f"slot 6 has a {list[6]}")
list.append(-113)
print(f"slot 7 has a {list[7]}")
list.append(-113)
print(f"slot 8 has a {list[8]}")
list.append(-113)
print(f"slot 9 has a {list[9]}")
